-- ============================================
-- 멀티플레이어 게임 시스템 DB 스키마
-- ============================================

-- 1. 맵/채널 테이블
CREATE TABLE IF NOT EXISTS public.maps (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  max_players INTEGER DEFAULT 50,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 초기 맵 데이터
INSERT INTO public.maps (id, name, description) VALUES
  ('starting_village', '시작 마을', '모험가들이 처음 시작하는 평화로운 마을'),
  ('forest', '숲', '마을 외곽의 울창한 숲'),
  ('dungeon_1', '던전 1층', '위험한 몬스터가 서식하는 던전')
ON CONFLICT (id) DO NOTHING;

-- 2. 채팅 메시지 테이블
CREATE TABLE IF NOT EXISTS public.chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  map_id TEXT REFERENCES public.maps(id) ON DELETE CASCADE,
  sender_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  sender_name TEXT NOT NULL,
  message_type TEXT DEFAULT 'normal' CHECK (message_type IN ('normal', 'whisper', 'system')),
  recipient_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  recipient_name TEXT,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 인덱스
CREATE INDEX IF NOT EXISTS idx_chat_messages_map ON public.chat_messages(map_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_chat_messages_whisper ON public.chat_messages(recipient_id) WHERE message_type = 'whisper';
CREATE INDEX IF NOT EXISTS idx_chat_messages_sender ON public.chat_messages(sender_id, created_at DESC);

-- 3. 유저 위치 테이블
CREATE TABLE IF NOT EXISTS public.user_locations (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  character_name TEXT NOT NULL,
  map_id TEXT REFERENCES public.maps(id) DEFAULT 'starting_village',
  position_x INTEGER DEFAULT 0,
  position_y INTEGER DEFAULT 0,
  last_active TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_locations_map ON public.user_locations(map_id);

-- ============================================
-- RLS 정책
-- ============================================

-- maps: 모든 인증 사용자 읽기 가능
ALTER TABLE public.maps ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view maps" ON public.maps
  FOR SELECT USING (true);

-- chat_messages: 인증된 사용자만 읽기/쓰기
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read messages in their map or whispers" ON public.chat_messages
  FOR SELECT USING (
    auth.uid() IS NOT NULL AND (
      -- 같은 맵의 일반 메시지
      (message_type = 'normal' AND map_id IN (
        SELECT map_id FROM public.user_locations WHERE user_id = auth.uid()
      ))
      -- 받은 귓말
      OR recipient_id = auth.uid()
      -- 보낸 귓말
      OR sender_id = auth.uid()
      -- 시스템 메시지
      OR message_type = 'system'
    )
  );

CREATE POLICY "Users can insert messages" ON public.chat_messages
  FOR INSERT WITH CHECK (auth.uid() = sender_id);

-- user_locations: 모든 인증 사용자 읽기, 본인만 수정
ALTER TABLE public.user_locations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view locations" ON public.user_locations
  FOR SELECT USING (auth.uid() IS NOT NULL);

CREATE POLICY "Users can insert own location" ON public.user_locations
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own location" ON public.user_locations
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own location" ON public.user_locations
  FOR DELETE USING (auth.uid() = user_id);

-- ============================================
-- Realtime 활성화
-- ============================================
ALTER PUBLICATION supabase_realtime ADD TABLE public.chat_messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.user_locations;

-- ============================================
-- 유틸리티 함수
-- ============================================

-- 유저 위치 업데이트 또는 생성 (upsert)
CREATE OR REPLACE FUNCTION public.upsert_user_location(
  p_user_id UUID,
  p_character_name TEXT,
  p_map_id TEXT DEFAULT 'starting_village'
)
RETURNS void AS $$
BEGIN
  INSERT INTO public.user_locations (user_id, character_name, map_id, last_active)
  VALUES (p_user_id, p_character_name, p_map_id, NOW())
  ON CONFLICT (user_id) DO UPDATE SET
    character_name = EXCLUDED.character_name,
    map_id = EXCLUDED.map_id,
    last_active = NOW();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 맵의 최근 채팅 메시지 가져오기
CREATE OR REPLACE FUNCTION public.get_recent_messages(
  p_map_id TEXT,
  p_limit INTEGER DEFAULT 50
)
RETURNS TABLE (
  id BIGINT,
  map_id TEXT,
  sender_id UUID,
  sender_name TEXT,
  message_type TEXT,
  recipient_id UUID,
  recipient_name TEXT,
  content TEXT,
  created_at TIMESTAMPTZ
) AS $$
BEGIN
  RETURN QUERY
  SELECT cm.id, cm.map_id, cm.sender_id, cm.sender_name,
         cm.message_type, cm.recipient_id, cm.recipient_name,
         cm.content, cm.created_at
  FROM public.chat_messages cm
  WHERE cm.map_id = p_map_id AND cm.message_type = 'normal'
  ORDER BY cm.created_at DESC
  LIMIT p_limit;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
